version: '3.8'

services:
  backend-template-db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
    volumes:
      - backend-template-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  backend-template-db-data:
